version: '3.2'                                                                                                             
services:                                                                                                                  
  test_webapp:                                                                                                                 
    build:                                                                                                                 
      context: test_webapp/                                                                                                    
    privileged: true                                                                                                       
    user: root                                                                                                             
    ports:                                                                                                                 
      - 5000:5000                                                                                                          
      - 80000:80000                                                                                                        
    container_name: MuscleMan                                                                                                
    volumes:                                                                                                               
      - /tmp/test_webapp:/var/test_webapp #Remember that, the tmp directory is designed to be wiped on system reboot.         
      - /var/run/docker.sock2:/var/run/docker.sock2                                                                          
