version: '3.2'                                                                                                             
services:                                                                                                                  
  totona3:                                                                                                                 
    build: 
     context: .                                                                                                   
     dockerfile: Dockerfile                                                                                                    
    user: root
    privileged: true                                                                                                             
    ports:                                                                                                                 
      - 5000:5000                                                                                                          
    container_name: MuscleMan
    volumes:                                                                                                               
      - /tmp/totona3:/var/totona3 #Remember that, the tmp directory is designed to be wiped on system reboot.         
      - /var/run/docker.sock2:/var/run/docker.sock2                                                                          
